version: "3.8"
services:
  db:
    image: mariadb:11.0.2
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_SECRET}
      TZ: ${TIME_ZONE}
    volumes:
      - database_volume:/var/lib/mysql
    ports:
      - ${DB_OUTSIDE_PORT}:3306

    networks:
      - digsearch-network

  head:
    image: ${TAG_COMMIT}
    depends_on:
      - db
    user: pwuser
    restart: always
    security_opt:
      - seccomp:seccomp_profile.json
    ipc: host
    stdin_open: true
    tty: true
    mem_limit: 2g
    ports:
      - ${FLASK_PORT}:5000
    environment:
      - DB_NAME=${APP_NAME}
      - DB_HOST=db
      - TZ=${TIME_ZONE}
    networks:
      - digsearch-network
      - default
    volumes:
      - ${APP_PATH}/.env:${DOCKER_APP_PATH}/.env

networks:
  digsearch-network:

volumes:
  database_volume:
